# Generated by Django 5.2.1 on 2025-05-21 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('impurezas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(max_length=100)),
                ('fecha_prueba', models.DateField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lote')),
            ],
        ),
    ]
